### ISSUE TITLE
Question: protoClassName not configured

### ISSUE THREAD

**Issue by smahad786** [blueapron/kafka-connect-protobuf-converter#13]
2019-01-24 01:20:27,948 INFO   ||  Instantiated task inventory-connector-0 with version 0.8.3.Final of type io.debezium.connector.postgresql.PostgresConnectorTask   [org.apache.kafka.connect.runtime.Worker]
2019-01-24 01:20:27,949 ERROR  ||  Failed to start task inventory-connector-0   [org.apache.kafka.connect.runtime.Worker]
org.apache.kafka.connect.errors.ConnectException: Value converter must have a protoClassName configured
        at com.blueapron.connect.protobuf.ProtobufConverter.configure(ProtobufConverter.java:33)
        at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:237)
        at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:402)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:857)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:109)
The protobuf class is in the data.jar....

My connect looks like this:
connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    environment:
     - KAFKA_CONNECT_PLUGINS_DIR=/kafka/connect,/connectors/blueapron-kafka-connect-protobuf-converter-2.0.0/lib
    ports:
     - 8083:8083
    volumes:
     - ./blueapron-kafka-connect-protobuf-converter-2.0.0/lib:/connectors/blueapron-kafka-connect-protobuf-converter-2.0.0/lib
     - ./data.jar:/kafka/connect/data.jar
     - ./blueapron-kafka-connect-protobuf-converter-2.0.0/lib/kafka-connect-protobuf-converter-2.0.0.jar:/kafka/connect/kafka-connect-protobuf-converter-2.0.0.jar
    links:
     - kafka
     - postgres
     - schema-registry
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     #- KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
     #- VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
     - VALUE_CONVERTER=com.blueapron.connect.protobuf.ProtobufConverter
     - KEY_CONVERTER=com.blueapron.connect.protobuf.ProtobufConverter
     - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
     - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
     #- value.converter=com.blueapron.connect.protobuf.ProtobufConverter
     #- key.converter=com.blueapron.connect.protobuf.ProtobufConverter
     #- value.converter.protoClassName=com.example.tutorial.Customer
     - VALUE_CONVERTER_PROTOCLASSNAME=com.example.tutorial.Customer

**Comment by makearl** [comment]
Hi @smahad786 , this project is designed to be used with Kafka Connect connectors. You can use most of the config you have above for Kafka Connect in docker, but don't specify `VALUE_CONVERTER_PROTOCLASSNAME` on a global level. Instead use it as `value,converter.protoClassName` in your individual connector configuration because you generally should have a different proto that can deserialize each topic. 

Also, you'll need to use the compiled class name, sometimes this means that you'll need to reference the inner class depending on how you have your proto set up. Example: `com.blueapron.connect.protobuf.NestedTestProtoOuterClass$NestedTestProto`. I would recommend first trying this project with one of Google's wrapped classes, like `com.google.protobuf.Int32Value`

**Comment by makearl** [comment]
Closing due to no response, please reopen if you have more questions

**Comment by sschatts** [comment]
Closing due to no response. Please reopen if you have more questions.
